# Generated by Django 3.1.5 on 2022-04-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategorimodel',
            table='Kategori',
        ),
    ]
