# Generated by Django 4.0.4 on 2022-04-30 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncelleme_tarihi',
            new_name='duzenleme_tarihi',
        ),
    ]
